module.exports = {
  endOfLine: 'lf',
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
  printWidth: 80,
  proseWrap: 'never',
  quoteProps: 'as-needed',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  useTabs: false,
  'editor.formatOnSave': true,
  'editor.formatOnPaste': false,
  'editor.formatOnType': false,
  'editor.defaultFormatter': 'esbenp.prettier-vscode',
}